config/routes.rb
Rails.application.routes.draw do

  get 'top_users/new'

  get 'top_users/create'

  resources :repairs
  resources :operators
  resources :servicemen
  resources :employees
  resources :reports
  resources :rents
  resources :bikes
  resources :stations
  resources :locations
  resources :users

  root 'homepage#index'

  get 'signup' => 'signup#index'
  get 'bikes' => 'bikes#index'
  get 'users' => 'users#index'
  get 'rents' => 'rents#index'
  get 'homepage' => 'homepage#index'

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :station
  has_many :rents
  has_many :repairs

  accepts_nested_attributes_for :rents

  after_destroy :decrement_bike_quantity
  after_create :increment_bike_quantity

  def station_id=(id)
    write_attribute(:station_id, id)
  end


  private

  def increment_bike_quantity
    self.station.increment!(:bike_quantity, 1)
  end

  def decrement_bike_quantity
    self.station.decrement!(:bike_quantity, 1)
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location


  def self.types
    %w(Serviceman Operator)
  end

  scope :operators, -> {where(type:'Operator')}
  scope :servicemen, -> {where(type:'Serviceman')}


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :user
  has_one :employee
  has_one :station

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :station

  def full_name
    self.street + " " + self.flat_number
  end
end

app/models/operator.rb
class Operator < Employee
  has_many :reports
end

app/models/rent.rb
class Rent   < ActiveRecord::Base
  belongs_to :user
  belongs_to :return_place, :class_name => 'Station', :foreign_key => 'return_place_id'
  belongs_to :rent_place, :class_name => 'Station', :foreign_key => 'rent_place_id'
  belongs_to :bike

after_create :relocate_bike

  def relocate_bike

      self.rent_place.decrement!(:bike_quantity, 1)
      self.bike.update_attribute(:station_id, self.return_place.id)
      self.return_place.increment!(:bike_quantity, 1)

  end

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :serviceman
  belongs_to :bike
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :operator

end

app/models/serviceman.rb
class Serviceman < Employee
  has_many :repairs
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
  has_many :bikes, dependent: :destroy
  has_many :rents

  accepts_nested_attributes_for :rents

  $station_capacity = 10

  validates :bike_quantity, presence: true, numericality: {:less_than_or_equal_to => $station_capacity}

  def ulica
    location.street
  end

  after_initialize :set_bike_quantity_0

  def set_bike_quantity_0
    self.bike_quantity ||= 0 if self.new_record?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
  has_many :rents
  has_many :reports

  accepts_nested_attributes_for :location

  def full_name
    return last_name + " " + first_name;
  end


end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="homepage">Bike rental</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->


    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if params[:controller] != ('signup') %>
        <% if params[:controller] != ('homepage') %>
          <li <% if params[:controller] == 'users' %>class="active"<% end %>><%= link_to "Użytkownicy", users_path %></li>
          <li <% if params[:controller] == 'bikes' %>class="active"<% end %>><%= link_to "Rowery", bikes_path %></li>
          <li <% if params[:controller] == 'rents' %>class="active"<% end %>><%= link_to "Wypożyczenia", rents_path %></li>
          <li <% if params[:controller] == 'stations' %>class="active"<% end %>><%= link_to "Stacje", stations_path %></li>
          <li <% if params[:controller] == 'locations' %>class="active"<% end %>><%= link_to "Lokalizacje", locations_path %></li>
        <% end %>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if params[:controller] == 'homepage' %>
            <li> <%= link_to "Załóż konto", signup_path %></li>
        <%end%>

      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>