config/routes.rb
Rails.application.routes.draw do

  get 'top_users/new'

  get 'top_users/create'

  resources :repairs
  resources :operators
  resources :servicemen
  resources :employees
  resources :reports
  resources :rents
  resources :bikes
  resources :stations
  resources :locations
  resources :users

  root 'homepage#index'

  get 'signup' => 'signup#index'
  get 'bikes' => 'bikes#index'
  get 'users' => 'users#index'
  get 'rents' => 'rents#index'
  get 'homepage' => 'homepage#index'

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :station
  has_many :rents
  has_many :repairs

  accepts_nested_attributes_for :rents

  after_destroy :decrement_bike_quantity
  after_create :increment_bike_quantity

  def station_id=(id)
    write_attribute(:station_id, id)
  end


  private

  def increment_bike_quantity
    self.station.increment!(:bike_quantity, 1)
  end

  def decrement_bike_quantity
    self.station.decrement!(:bike_quantity, 1)
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location


  def self.types
    %w(Serviceman Operator)
  end

  scope :operators, -> {where(type:'Operator')}
  scope :servicemen, -> {where(type:'Serviceman')}


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :user
  has_one :employee
  has_one :station

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :station

  def full_name
    self.street + " " + self.flat_number
  end
end

app/models/operator.rb
class Operator < Employee
  has_many :reports
end

app/models/rent.rb
class Rent   < ActiveRecord::Base
  belongs_to :user
  belongs_to :return_place, :class_name => 'Station', :foreign_key => 'return_place_id'
  belongs_to :rent_place, :class_name => 'Station', :foreign_key => 'rent_place_id'
  belongs_to :bike

after_create :relocate_bike

  def relocate_bike

      self.rent_place.decrement!(:bike_quantity, 1)
      self.bike.update_attribute(:station_id, self.return_place.id)
      self.return_place.increment!(:bike_quantity, 1)

  end

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :serviceman
  belongs_to :bike
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :operator

end

app/models/serviceman.rb
class Serviceman < Employee
  has_many :repairs
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
  has_many :bikes, dependent: :destroy
  has_many :rents

  accepts_nested_attributes_for :rents

  $station_capacity = 10

  validates :bike_quantity, presence: true, numericality: {:less_than_or_equal_to => $station_capacity}

  def ulica
    location.street
  end

  after_initialize :set_bike_quantity_0

  def set_bike_quantity_0
    self.bike_quantity ||= 0 if self.new_record?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
  has_many :rents
  has_many :reports

  accepts_nested_attributes_for :location

  def full_name
    return last_name + " " + first_name;
  end


end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  before_action :set_bike, only: [:show, :edit, :update, :destroy]

  # GET /bikes
  # GET /bikes.json
  def index
    @bikes = Bike.all
  end

  # GET /bikes/1
  # GET /bikes/1.json
  def show
  end

  # GET /bikes/new
  def new
    @bike = Bike.new
  end

  # GET /bikes/1/edit
  def edit
  end

  # POST /bikes
  # POST /bikes.json
  def create
    @bike = Bike.new(bike_params)

    respond_to do |format|
      if @bike.save
        format.html { redirect_to @bike, notice: 'Bike was successfully created.' }
        format.json { render :show, status: :created, location: @bike }
      else
        format.html { render :new }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bikes/1
  # PATCH/PUT /bikes/1.json
  def update
    respond_to do |format|
      if @bike.update(bike_params)
        format.html { redirect_to @bike, notice: 'Bike was successfully updated.' }
        format.json { render :show, status: :ok, location: @bike }
      else
        format.html { render :edit }
        format.json { render json: @bike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bikes/1
  # DELETE /bikes/1.json
  def destroy
    @bike.destroy
    respond_to do |format|
      format.html { redirect_to bikes_url, notice: 'Bike was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bike
      @bike = Bike.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bike_params
      params.require(:bike).permit(:station_id, :bike_status)
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servicemen_helper.rb
module ServicemenHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bikes/_form.html.erb
<%= form_for(@bike) do |f| %>
  <% if @bike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bike.errors.count, "error") %> prohibited this bike from being saved:</h2>

      <ul>
      <% @bike.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

   <div class="field">
    <%= f.label :station_id %><br>
    <%= f.collection_select(:station_id, Station.where("bike_quantity <= ?", 9), :id, :ulica) %>
   </div>

  <div class="field">
    <%= f.label :bike_status %><br>
    <%= f.text_field :bike_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bikes/edit.html.erb
<h1>Editing Bike</h1>

<%= render 'form' %>

<%= link_to 'Show', @bike %> |
<%= link_to 'Back', bikes_path %>

app/views/bikes/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Bike Number</th>
      <th>Station</th>
      <th>Bike status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bikes.each do |bike| %>
      <tr>
        <td><%= bike.id %></td>
        <td><%= bike.station.location.street %> <%= bike.station.location.flat_number %></td>
        <td><%= bike.bike_status %></td>
        <td><%= link_to 'Show', bike %></td>
        <td><%= link_to 'Edit', edit_bike_path(bike) %></td>
        <td><%= link_to 'Destroy', bike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bike', new_bike_path %>

app/views/bikes/new.html.erb
<h1>New Bike</h1>

<%= render 'form' %>

<%= link_to 'Back', bikes_path %>

app/views/bikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Station:</strong>
  <%= @bike.station_id %>
</p>

<p>
  <strong>Bike status:</strong>
  <%= @bike.bike_status %>
</p>

<%= link_to 'Edit', edit_bike_path(@bike) %> |
<%= link_to 'Back', bikes_path %>