config/routes.rb
Rails.application.routes.draw do

  get 'top_users/new'

  get 'top_users/create'

  resources :repairs
  resources :operators
  resources :servicemen
  resources :employees
  resources :reports
  resources :rents
  resources :bikes
  resources :stations
  resources :locations
  resources :users

  root 'homepage#index'

  get 'signup' => 'signup#index'
  get 'bikes' => 'bikes#index'
  get 'users' => 'users#index'
  get 'rents' => 'rents#index'
  get 'homepage' => 'homepage#index'

end

app/models/bike.rb
class Bike < ActiveRecord::Base
  belongs_to :station
  has_many :rents
  has_many :repairs

  accepts_nested_attributes_for :rents

  after_destroy :decrement_bike_quantity
  after_create :increment_bike_quantity

  def station_id=(id)
    write_attribute(:station_id, id)
  end


  private

  def increment_bike_quantity
    self.station.increment!(:bike_quantity, 1)
  end

  def decrement_bike_quantity
    self.station.decrement!(:bike_quantity, 1)
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  belongs_to :location


  def self.types
    %w(Serviceman Operator)
  end

  scope :operators, -> {where(type:'Operator')}
  scope :servicemen, -> {where(type:'Serviceman')}


end

app/models/location.rb
class Location < ActiveRecord::Base
  has_one :user
  has_one :employee
  has_one :station

  accepts_nested_attributes_for :user
  accepts_nested_attributes_for :station

  def full_name
    self.street + " " + self.flat_number
  end
end

app/models/operator.rb
class Operator < Employee
  has_many :reports
end

app/models/rent.rb
class Rent   < ActiveRecord::Base
  belongs_to :user
  belongs_to :return_place, :class_name => 'Station', :foreign_key => 'return_place_id'
  belongs_to :rent_place, :class_name => 'Station', :foreign_key => 'rent_place_id'
  belongs_to :bike

after_create :relocate_bike

  def relocate_bike

      self.rent_place.decrement!(:bike_quantity, 1)
      self.bike.update_attribute(:station_id, self.return_place.id)
      self.return_place.increment!(:bike_quantity, 1)

  end

end

app/models/repair.rb
class Repair < ActiveRecord::Base
  belongs_to :serviceman
  belongs_to :bike
end

app/models/report.rb
class Report < ActiveRecord::Base
  belongs_to :user
  belongs_to :operator

end

app/models/serviceman.rb
class Serviceman < Employee
  has_many :repairs
end

app/models/station.rb
class Station < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
  has_many :bikes, dependent: :destroy
  has_many :rents

  accepts_nested_attributes_for :rents

  $station_capacity = 10

  validates :bike_quantity, presence: true, numericality: {:less_than_or_equal_to => $station_capacity}

  def ulica
    location.street
  end

  after_initialize :set_bike_quantity_0

  def set_bike_quantity_0
    self.bike_quantity ||= 0 if self.new_record?
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  belongs_to :location, dependent: :destroy
  has_many :rents
  has_many :reports

  accepts_nested_attributes_for :location

  def full_name
    return last_name + " " + first_name;
  end


end

app/controllers/repairs_controller.rb
class RepairsController < ApplicationController
  before_action :set_repair, only: [:show, :edit, :update, :destroy]

  # GET /repairs
  # GET /repairs.json
  def index
    @repairs = Repair.all
  end

  # GET /repairs/1
  # GET /repairs/1.json
  def show
  end

  # GET /repairs/new
  def new
    @repair = Repair.new
  end

  # GET /repairs/1/edit
  def edit
  end

  # POST /repairs
  # POST /repairs.json
  def create
    @repair = Repair.new(repair_params)

    respond_to do |format|
      if @repair.save
        format.html { redirect_to @repair, notice: 'Repair was successfully created.' }
        format.json { render :show, status: :created, location: @repair }
      else
        format.html { render :new }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repairs/1
  # PATCH/PUT /repairs/1.json
  def update
    respond_to do |format|
      if @repair.update(repair_params)
        format.html { redirect_to @repair, notice: 'Repair was successfully updated.' }
        format.json { render :show, status: :ok, location: @repair }
      else
        format.html { render :edit }
        format.json { render json: @repair.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repairs/1
  # DELETE /repairs/1.json
  def destroy
    @repair.destroy
    respond_to do |format|
      format.html { redirect_to repairs_url, notice: 'Repair was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repair
      @repair = Repair.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repair_params
      params.require(:repair).permit(:bike_id, :serviceman_id, :start_time, :end_time, :repair_status)
    end
end

app/helpers/bikes_helper.rb
module BikesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/operators_helper.rb
module OperatorsHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/helpers/repairs_helper.rb
module RepairsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/servicemen_helper.rb
module ServicemenHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/repairs/_form.html.erb
<%= form_for(@repair) do |f| %>
  <% if @repair.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@repair.errors.count, "error") %> prohibited this repair from being saved:</h2>

      <ul>
      <% @repair.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :bike_id %><br>
    <%= f.number_field :bike_id %>
  </div>
  <div class="field">
    <%= f.label :serviceman_id %><br>
    <%= f.number_field :serviceman_id %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :repair_status %><br>
    <%= f.text_field :repair_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/repairs/edit.html.erb
<h1>Editing Repair</h1>

<%= render 'form' %>

<%= link_to 'Show', @repair %> |
<%= link_to 'Back', repairs_path %>

app/views/repairs/index.html.erb
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Bike</th>
      <th>Serviceman</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Repair status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @repairs.each do |repair| %>
      <tr>
        <td><%= repair.bike_id %></td>
        <td><%= repair.serviceman_id %></td>
        <td><%= repair.start_time %></td>
        <td><%= repair.end_time %></td>
        <td><%= repair.repair_status %></td>
        <td><%= link_to 'Show', repair %></td>
        <td><%= link_to 'Edit', edit_repair_path(repair) %></td>
        <td><%= link_to 'Destroy', repair, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Repair', new_repair_path %>

app/views/repairs/new.html.erb
<h1>New Repair</h1>

<%= render 'form' %>

<%= link_to 'Back', repairs_path %>

app/views/repairs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Bike:</strong>
  <%= @repair.bike_id %>
</p>

<p>
  <strong>Serviceman:</strong>
  <%= @repair.serviceman_id %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @repair.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @repair.end_time %>
</p>

<p>
  <strong>Repair status:</strong>
  <%= @repair.repair_status %>
</p>

<%= link_to 'Edit', edit_repair_path(@repair) %> |
<%= link_to 'Back', repairs_path %>